---
- name: Converge
  hosts: all
  roles:
    - role: mysql
    - role: apache
    - role: php
    - role: composer
    - role: ansible-role-snipeit
  pre_tasks:
    - name: Set default Ubuntu 16.04 php version
      set_fact:
        php_default_version_debian: "7.0"
      when: ansible_distribution_release == 'xenial'
      changed_when: false

    - name: Set default Ubuntu 18.04 php version
      set_fact:
        php_default_version_debian: "7.2"
      when: ansible_distribution_release == 'bionic'
      changed_when: false
  vars:
    snipeit_env_MAIL_HOST: "not.a.real.email.server"
    mysql_packages:
      - mariadb-client
      - mariadb-server

    mysql_root_password: "password"
    mysql_root_password_update: false

    mysql_databases:
      - name: "{{ snipeit_env_DB_DATABASE }}"
        encoding: utf8
        collation: utf8_bin

    mysql_users:
      - name: "{{ snipeit_env_DB_USERNAME }}"
        host: "%"
        password: "{{ snipeit_env_DB_PASSWORD }}"
        priv: "{{ snipeit_env_DB_DATABASE }}.*:ALL"

    mysql_innodb_buffer_pool_size: "256M"
    mysql_innodb_log_file_size: "64M"

    # Apache settings
    apache_sites:
      - id: "{{ ansible_fqdn }}"
        name: "{{ ansible_fqdn }}"
        state: present
        webroot: "{{ snipeit_root_directory }}/public"
        port: 80
        add_webroot: false
        server_status_ip:
          - { ip: '172.17.0.0/8'}  # Docker IP Range for local testing
          - { ip: '127.0.0.0/8' }
          - { ip: '::1' }
        aliases: []
        rules:
          - character_encodings.conf
          - custom_errors.conf
          - media_types.conf
          - rewrite_engine.conf
          - rewrite_www.conf
          - strict-transport-security.conf
        append: |
          RewriteEngine On
          # From public/.htaccess
          RewriteCond %{DOCUMENT_ROOT}%{REQUEST_FILENAME} !-d
          RewriteCond %{REQUEST_URI} (.+)/$
          RewriteRule ^ %1 [L,R=301]
          RewriteCond %{DOCUMENT_ROOT}%{REQUEST_FILENAME} !-d
          RewriteCond %{DOCUMENT_ROOT}%{REQUEST_FILENAME} !-f
          RewriteRule ^ /index.php [L]

    # PHP settings
    php_packages_extra:
      - "php{{ php_default_version_debian }}"
      - "php{{ php_default_version_debian }}-mysql"
      - "php{{ php_default_version_debian }}-ldap"
      - "libapache2-mod-php"
      - "php{{ php_default_version_debian }}-gd"
      - "php{{ php_default_version_debian }}-curl"
      - "php{{ php_default_version_debian }}-mbstring"
      - "php{{ php_default_version_debian }}-zip"
      - "php{{ php_default_version_debian }}-fileinfo"
      - "php{{ php_default_version_debian }}-bcmath"
      - "php{{ php_default_version_debian }}-xml"
      - "php{{ php_default_version_debian }}-pdo"
      - "php{{ php_default_version_debian }}-tokenizer"
    php_memory_limit: "256M"
    php_max_execution_time: "60"
    php_max_input_time: "60"
    php_max_input_vars: "1000"
    php_upload_max_filesize: "64M"
    php_max_file_uploads: "20"
    php_post_max_size: "32M"
    php_date_timezone: "America/New_York"
